### ISSUE TITLE
Is Linked List insert always O(n)? 

### ISSUE THREAD

**Issue by Polyergic** [samvv/typescript-containers#4]
According to your README, the time for an insert into either SingleLinkedList or DoubleLinkedList is O(n).  That should not be the case for all inserts, only for inserts that require seeking.

|             | insertAt | insertBefore | insertAfter |
|--------|---------|--------------|-------------|
| Single  | O(n)       | O(n)              | O(1)        |
| Double | O(n)      | O(1)               | O(1)        |

I tried to look at your code to see if it was actually O(n), but did not see the source for insertBefore (the only insert method I saw in your README) in the obvious places.

**Comment by samvv** [comment]
Sorry, there seems to be have gone something wrong with my notifications during the previous period. If it still is an issue, then I'd just like to tell you that you're right. It shouldn't be O(n). I'll be pushing a new version with updated code and documentation (note that there might be breaking changes).

**Comment by samvv** [comment]
Good news: the insertion operation is now O(1), provided that you know the position where you want to insert upfront. This should close this issue. Let me know if you still have any questions.
